Extension { #name : #MiNAryQueryPresenter }

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNAryQueryPresenter >> addSubqueryToLayoutButton [
	^ addSubqueryToLayoutButton
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNAryQueryPresenter >> removeSubqueryFromLayoutButton [
	^ removeSubqueryFromLayoutButton
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNAryQueryPresenter >> subqueryDropLists [
	^ subqueryDropLists
]
