Extension { #name : #MiNewQueryCreationPresenter }

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueryCreationPresenter >> parentPresenter [
	^ parentPresenter
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueryCreationPresenter >> parentQuery: aQuery [

	parentQuery := aQuery
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueryCreationPresenter >> queryConfigurationPresenter [

	^ queryConfigurationPresenter
]
