Extension { #name : #MiNewQueriesBrowser }

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueriesBrowser >> queryCodePresenter [

	^ queryCodePresenter
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueriesBrowser >> queryResultTreePresenter [

	^ queryResultTreePresenter
]

{ #category : #'*MooseIDE-NewTools-Tests' }
MiNewQueriesBrowser >> selectedQuery [

	"This method is only for backwards compatibility with the old queries browser"

	^ selectedQuery
]
