Extension { #name : #MiNewQueriesBrowser }

{ #category : #'*Midas-NewTools-Tests' }
MiNewQueriesBrowser >> queriesHistory [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queriesHistory
]

{ #category : #'*Midas-NewTools-Tests' }
MiNewQueriesBrowser >> queryCodePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryCodePresenter
]

{ #category : #'*Midas-NewTools-Tests' }
MiNewQueriesBrowser >> queryResultTreePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryResultTreePresenter
]
