Extension { #name : #MiAbstractBrowser }

{ #category : #'*MooseIDE-Tests' }
MiAbstractBrowser >> busButton [
	^ busButton
]

{ #category : #'*MooseIDE-Tests' }
MiAbstractBrowser >> follow [
	buttonFollow state: true
]

{ #category : #'*MooseIDE-Tests' }
MiAbstractBrowser >> freeze [
	buttonFreeze state: true
]

{ #category : #'*MooseIDE-Tests' }
MiAbstractBrowser >> highlight [
	buttonHighlight state: true
]
