Class {
	#name : #MiNoteBookCodeScriptingInteractionModel,
	#superclass : #SpCodeScriptingInteractionModel,
	#instVars : [
		'receiver'
	],
	#category : #'MooseIDE-Export-Notebook'
}

{ #category : #accessing }
MiNoteBookCodeScriptingInteractionModel >> doItReceiver [

	^ receiver
]

{ #category : #accessing }
MiNoteBookCodeScriptingInteractionModel >> receiver [

	^ receiver
]

{ #category : #accessing }
MiNoteBookCodeScriptingInteractionModel >> receiver: anObject [

	receiver := anObject
]
