Extension { #name : #MiCBConditionBuilderPresenter }

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBConditionBuilderPresenter >> conditionSummary [
"used for testing purposes, do not access outside of tests"
	^ summaryField
]

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBConditionBuilderPresenter >> conditionTitle [
"used for testing purposes, do not access outside of tests"
	^ titleField
]

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBConditionBuilderPresenter >> queryDroplist [
	^ queryDroplist
]
