Extension { #name : #MiCBContextBuilderPresenter }

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBContextBuilderPresenter >> codeInput [ 
"used for testing purposes, do not access outside of tests"
	^ codeInput
]

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBContextBuilderPresenter >> contextSummary [
"used for testing purposes, do not access outside of tests"
	^ contextSummary
]

{ #category : #'*MooseIDE-CriticBrowser-Tests' }
MiCBContextBuilderPresenter >> contextTitle [
"used for testing purposes, do not access outside of tests"
	^ contextTitle
]
