Extension { #name : #MiNAryQueryPresenter }

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiNAryQueryPresenter >> addSubqueryToLayoutButton [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ addSubqueryToLayoutButton
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiNAryQueryPresenter >> removeSubqueryFromLayoutButton [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ removeSubqueryFromLayoutButton
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiNAryQueryPresenter >> subqueryDropLists [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ subqueryDropLists
]
