Extension { #name : #MiNewQueriesBrowser }

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiNewQueriesBrowser >> queryCodePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryCodePresenter
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiNewQueriesBrowser >> queryResultTreePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryResultTreePresenter
]
