Extension { #name : #MiPropertyQueryPresenter }

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiPropertyQueryPresenter >> comparatorDropList [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ comparatorDropList
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiPropertyQueryPresenter >> propertyDropList [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ propertyDropList
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiPropertyQueryPresenter >> valueInputField [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ valueInputField
]
