Extension { #name : #MiQueriesBrowser }

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiQueriesBrowser >> queriesListPresenter [
	^ queriesListPresenter
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiQueriesBrowser >> queryCodePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryCodePresenter
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiQueriesBrowser >> queryResultTreePresenter [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ queryResultTreePresenter
]
