Extension { #name : #MiTypeQueryPresenter }

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiTypeQueryPresenter >> typesButton [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ typesButton
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiTypeQueryPresenter >> typesList [
	^ typesList
]

{ #category : #'*MooseIDE-QueriesBrowser-Tests' }
MiTypeQueryPresenter >> typesModal [

	self flag: 'Do not use this accessor. This is only for the tests'.
	^ typesModal
]
