Extension { #name : #MiPropertyQueryPresenter }

{ #category : #'*Midas-FamixQueries-Tests' }
MiPropertyQueryPresenter >> comparators [
	^ secondParameter presenterAt: #comparators
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiPropertyQueryPresenter >> properties [
	^ secondParameter presenterAt: #properties
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiPropertyQueryPresenter >> valueInput [
	^ secondParameter presenterAt: #valueInput
]
