Extension { #name : #MiQueriesCombinationPresenter }

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> browser [
	^ browser
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> combinationsDroplist [
	^ combinationsDroplist
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> parentQueries [
	^ parentQueries
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> queriesTree [
	^ queriesTree
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> resultList [
	^ resultList
]

{ #category : #'*Midas-FamixQueries-Tests' }
MiQueriesCombinationPresenter >> toolBar [
	^ toolBar
]
